SOURCE_DIR=.
PATH_SPILT=:
JAR=$(SOURCE_DIR)$(PATH_SPILT)javahelp-2.0.05.jar$(PATH_SPILT)jnlp-1.5.0.jar

all: \
	autoroute/AutorouteControl.class \
	autoroute/AutorouteEngine.class \
	autoroute/BatchAutorouter.class \
	autoroute/BatchFanout.class \
	autoroute/BatchOptRoute.class \
	autoroute/CompleteExpansionRoom.class \
	autoroute/CompleteFreeSpaceExpansionRoom.class \
	autoroute/Connection.class \
	autoroute/DestinationDistance.class \
	autoroute/DrillPage.class \
	autoroute/DrillPageArray.class \
	autoroute/ExpandableObject.class \
	autoroute/ExpansionDoor.class \
	autoroute/ExpansionDrill.class \
	autoroute/ExpansionRoom.class \
	autoroute/FreeSpaceExpansionRoom.class \
	autoroute/IncompleteFreeSpaceExpansionRoom.class \
	autoroute/InsertFoundConnectionAlgo.class \
	autoroute/ItemAutorouteInfo.class \
	autoroute/LocateFoundConnectionAlgo.class \
	autoroute/LocateFoundConnectionAlgo45Degree.class \
	autoroute/LocateFoundConnectionAlgoAnyAngle.class \
	autoroute/MazeListElement.class \
	autoroute/MazeSearchAlgo.class \
	autoroute/MazeSearchElement.class \
	autoroute/MazeShoveTraceAlgo.class \
	autoroute/ObstacleExpansionRoom.class \
	autoroute/Sorted45DegreeRoomNeighbours.class \
	autoroute/SortedOrthogonalRoomNeighbours.class \
	autoroute/SortedRoomNeighbours.class \
	autoroute/TargetItemExpansionDoor.class \
	board/AngleRestriction.class \
	board/BasicBoard.class \
	board/BoardObserverAdaptor.class \
	board/BoardObservers.class \
	board/BoardOutline.class \
	board/CalcFromSide.class \
	board/CalcShapeAndFromSide.class \
	board/ChangedArea.class \
	board/ClearanceViolation.class \
	board/Communication.class \
	board/Component.class \
	board/ComponentObstacleArea.class \
	board/ComponentOutline.class \
	board/Components.class \
	board/ConductionArea.class \
	board/Connectable.class \
	board/CoordinateTransform.class \
	board/DrillItem.class \
	board/FixedState.class \
	board/ForcedPadAlgo.class \
	board/ForcedViaAlgo.class \
	board/Item.class \
	board/ItemIdNoGenerator.class \
	board/ItemSearchTreesInfo.class \
	board/ItemSelectionFilter.class \
	board/Layer.class \
	board/LayerStructure.class \
	board/MoveComponent.class \
	board/MoveDrillItemAlgo.class \
	board/ObjectInfoPanel.class \
	board/ObstacleArea.class \
	board/OptViaAlgo.class \
	board/Pin.class \
	board/PolylineTrace.class \
	board/PrintableShape.class \
	board/PullTightAlgo.class \
	board/PullTightAlgo45.class \
	board/PullTightAlgo90.class \
	board/PullTightAlgoAnyAngle.class \
	board/RoutingBoard.class \
	board/SearchTreeManager.class \
	board/SearchTreeObject.class \
	board/ShapeSearchTree.class \
	board/ShapeSearchTree45Degree.class \
	board/ShapeSearchTree90Degree.class \
	board/ShapeTraceEntries.class \
	board/ShoveTraceAlgo.class \
	board/TestLevel.class \
	board/Trace.class \
	board/Unit.class \
	board/Via.class \
	board/ViaObstacleArea.class \
	boardgraphics/ColorIntensityTable.class \
	boardgraphics/ColorTableModel.class \
	boardgraphics/CoordinateTransform.class \
	boardgraphics/Drawable.class \
	boardgraphics/GraphicsContext.class \
	boardgraphics/ItemColorTableModel.class \
	boardgraphics/ItemDrawInfo.class \
	boardgraphics/OtherColorTableModel.class \
	datastructures/ArrayStack.class \
	datastructures/BigIntAux.class \
	datastructures/FileFilter.class \
	datastructures/IdNoGenerator.class \
	datastructures/IdentifierType.class \
	datastructures/IndentFileWriter.class \
	datastructures/MinAreaTree.class \
	datastructures/Observers.class \
	datastructures/PlanarDelaunayTriangulation.class \
	datastructures/ShapeTree.class \
	datastructures/Signum.class \
	datastructures/Stoppable.class \
	datastructures/TimeLimit.class \
	datastructures/UndoableObjects.class \
	designformats/specctra/AutorouteSettings.class \
	designformats/specctra/Circle.class \
	designformats/specctra/Circuit.class \
	designformats/specctra/Component.class \
	designformats/specctra/ComponentPlacement.class \
	designformats/specctra/CoordinateTransform.class \
	designformats/specctra/DsnFile.class \
	designformats/specctra/Keyword.class \
	designformats/specctra/Layer.class \
	designformats/specctra/LayerStructure.class \
	designformats/specctra/Library.class \
	designformats/specctra/Net.class \
	designformats/specctra/NetClass.class \
	designformats/specctra/NetList.class \
	designformats/specctra/Network.class \
	designformats/specctra/Package.class \
	designformats/specctra/Parser.class \
	designformats/specctra/PartLibrary.class \
	designformats/specctra/Path.class \
	designformats/specctra/PlaceControl.class \
	designformats/specctra/Placement.class \
	designformats/specctra/Plane.class \
	designformats/specctra/Polygon.class \
	designformats/specctra/PolygonPath.class \
	designformats/specctra/PolylinePath.class \
	designformats/specctra/ReadScopeParameter.class \
	designformats/specctra/Rectangle.class \
	designformats/specctra/Resolution.class \
	designformats/specctra/Rule.class \
	designformats/specctra/RulesFile.class \
	designformats/specctra/Scanner.class \
	designformats/specctra/ScopeKeyword.class \
	designformats/specctra/SessionFile.class \
	designformats/specctra/SessionToEagle.class \
	designformats/specctra/Shape.class \
	designformats/specctra/SpecctraFileScanner.class \
	designformats/specctra/Structure.class \
	designformats/specctra/Wiring.class \
	designformats/specctra/WriteScopeParameter.class \
	geometry/planar/Area.class \
	geometry/planar/BigIntDirection.class \
	geometry/planar/Circle.class \
	geometry/planar/ConvexShape.class \
	geometry/planar/Direction.class \
	geometry/planar/Ellipse.class \
	geometry/planar/FloatLine.class \
	geometry/planar/FloatPoint.class \
	geometry/planar/FortyfiveDegreeBoundingDirections.class \
	geometry/planar/FortyfiveDegreeDirection.class \
	geometry/planar/IntBox.class \
	geometry/planar/IntDirection.class \
	geometry/planar/IntOctagon.class \
	geometry/planar/IntPoint.class \
	geometry/planar/IntVector.class \
	geometry/planar/Limits.class \
	geometry/planar/Line.class \
	geometry/planar/LineSegment.class \
	geometry/planar/OrthogonalBoundingDirections.class \
	geometry/planar/Point.class \
	geometry/planar/Polygon.class \
	geometry/planar/PolygonShape.class \
	geometry/planar/Polyline.class \
	geometry/planar/PolylineArea.class \
	geometry/planar/PolylineShape.class \
	geometry/planar/RationalPoint.class \
	geometry/planar/RationalVector.class \
	geometry/planar/RegularTileShape.class \
	geometry/planar/Shape.class \
	geometry/planar/ShapeBoundingDirections.class \
	geometry/planar/Side.class \
	geometry/planar/Simplex.class \
	geometry/planar/TileShape.class \
	geometry/planar/Vector.class \
	gui/BoardFrame.class \
	gui/BoardMenuBar.class \
	gui/BoardMenuDisplay.class \
	gui/BoardMenuFile.class \
	gui/BoardMenuHelp.class \
	gui/BoardMenuHelpReduced.class \
	gui/BoardMenuInfo.class \
	gui/BoardMenuOther.class \
	gui/BoardMenuParameter.class \
	gui/BoardMenuRules.class \
	gui/BoardPanel.class \
	gui/BoardPanelStatus.class \
	gui/BoardSavableSubWindow.class \
	gui/BoardSubWindow.class \
	gui/BoardTemporarySubWindow.class \
	gui/BoardToolbar.class \
	gui/BoardToolbarSelectedItem.class \
	gui/ColorManager.class \
	gui/ComboBoxClearance.class \
	gui/ComboBoxLayer.class \
	gui/Cursor.class \
	gui/DesignFile.class \
	gui/GUIDefaultsFile.class \
	gui/GUIDefaultsScanner.class \
	gui/MainApplication.class \
	gui/PopupMenuChangeLayer.class \
	gui/PopupMenuCopy.class \
	gui/PopupMenuDisplay.class \
	gui/PopupMenuDynamicRoute.class \
	gui/PopupMenuInsertCancel.class \
	gui/PopupMenuMain.class \
	gui/PopupMenuMove.class \
	gui/PopupMenuSelectedItems.class \
	gui/PopupMenuStitchRoute.class \
	gui/PupupMenuCornerItemConstruction.class \
	gui/WebStart.class \
	gui/WindowAbout.class \
	gui/WindowAssignNetClass.class \
	gui/WindowAutorouteDetailParameter.class \
	gui/WindowAutorouteParameter.class \
	gui/WindowClearanceMatrix.class \
	gui/WindowClearanceViolations.class \
	gui/WindowComponents.class \
	gui/WindowDisplayMisc.class \
	gui/WindowEditVias.class \
	gui/WindowIncompletes.class \
	gui/WindowLayerVisibility.class \
	gui/WindowLengthViolations.class \
	gui/WindowManualRules.class \
	gui/WindowMessage.class \
	gui/WindowMoveParameter.class \
	gui/WindowNetClasses.class \
	gui/WindowNetDemonstrations.class \
	gui/WindowNetSampleDesigns.class \
	gui/WindowNetSamples.class \
	gui/WindowNets.class \
	gui/WindowObjectInfo.class \
	gui/WindowObjectList.class \
	gui/WindowObjectListWithFilter.class \
	gui/WindowObjectVisibility.class \
	gui/WindowPackages.class \
	gui/WindowPadstacks.class \
	gui/WindowRouteDetail.class \
	gui/WindowRouteParameter.class \
	gui/WindowRouteStubs.class \
	gui/WindowSelectParameter.class \
	gui/WindowSnapshot.class \
	gui/WindowSnapshotSettings.class \
	gui/WindowUnconnectedRoute.class \
	gui/WindowVia.class \
	gui/WindowViaRule.class \
	gui/WindowVisibility.class \
	interactive/AutorouteSettings.class \
	interactive/BatchAutorouterThread.class \
	interactive/BoardHandling.class \
	interactive/CircleConstructionState.class \
	interactive/ClearanceViolations.class \
	interactive/CopyItemState.class \
	interactive/CornerItemConstructionState.class \
	interactive/CutoutRouteState.class \
	interactive/DragItemState.class \
	interactive/DragMenuState.class \
	interactive/DragState.class \
	interactive/DynamicRouteState.class \
	interactive/ExpandTestState.class \
	interactive/HoleConstructionState.class \
	interactive/InteractiveActionThread.class \
	interactive/InteractiveState.class \
	interactive/Logfile.class \
	interactive/LogfileScanner.class \
	interactive/LogfileScope.class \
	interactive/MakeSpaceState.class \
	interactive/MenuState.class \
	interactive/MoveItemState.class \
	interactive/NetIncompletes.class \
	interactive/PinSwapState.class \
	interactive/PolygonShapeConstructionState.class \
	interactive/RatsNest.class \
	interactive/Route.class \
	interactive/RouteMenuState.class \
	interactive/RouteState.class \
	interactive/ScreenMessages.class \
	interactive/SelectItemsInRegionState.class \
	interactive/SelectMenuState.class \
	interactive/SelectRegionState.class \
	interactive/SelectedItemState.class \
	interactive/Settings.class \
	interactive/SnapShot.class \
	interactive/StitchRouteState.class \
	interactive/TileConstructionState.class \
	interactive/ZoomRegionState.class \
	library/BoardLibrary.class \
	library/LogicalPart.class \
	library/LogicalParts.class \
	library/Package.class \
	library/Packages.class \
	library/Padstack.class \
	library/Padstacks.class \
	rules/BoardRules.class \
	rules/ClearanceMatrix.class \
	rules/DefaultItemClearanceClasses.class \
	rules/Net.class \
	rules/NetClass.class \
	rules/NetClasses.class \
	rules/Nets.class \
	rules/ViaInfo.class \
	rules/ViaInfos.class \
	rules/ViaRule.class \
	tests/Validate.class
	java -cp '$(JAR)' gui.MainApplication $(ARGS)

%.class: %.java
	javac -g -encoding utf8 -cp '$(JAR)'  $<
